name: Test
on:
  workflow_dispatch

jobs:
  update_leaderboard:
    runs-on: ubuntu-latest
    name: Update the Leaderboard
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Health Endpoint
        env:
          ITBENCH_API: ${{vars.ITBENCH_API}}
          ITBENCH_API_TOKEN: ${{ secrets.ITBENCH_API_TOKEN }}
        run: |
          curl $ITBENCH_API/health

          
         


      
      
